# GitHub Actions References:
# https://docs.github.com/en/actions/reference

name: Test, Build, and Deploy ⚙⚛✨🚀

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test_build:
    name: Test and Build ⚙⚛

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4

      - name: Use NodeJS ${{ matrix.node }} 📦
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install Dependencies ✨
        run: yarn --immutable --check-cache

      - name: Run Linter 👨🏻‍💻
        run: yarn type-check && yarn lint

      - name: Run Formatter 💅
        run: yarn format

      - name: Run Test 🛠
        run: yarn test

      - name: Run Build ⚙
        run: yarn build

      - name: Cache build ready to deploy 🚀
        uses: actions/cache@v2.1.6
        with:
          path: |
            ./dist
          key: ${{ github.sha }}-${{ runner.os }}-${{ matrix.node-version }}

  deploy:
    name: Deploy to production ✨🚀

    needs: test_build

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4

      - name: Restore build cache ♻️
        uses: actions/cache@v2.1.6
        with:
          path: |
            ./dist
          key: ${{ github.sha }}-${{ runner.os }}-${{ matrix.node-version }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
          git-config-name: latipun7
          git-config-email: latifsulistyo.me@gmail.com
